name: ubuntu-latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: "Build/Test" # contains slash so use quotes otherwise UB
      run: |
        python3 -V
        curl -Lo mkn https://github.com/mkn/mkn/releases/download/latest/mkn_nix
        chmod +x mkn
        KLOG=3 ./mkn clean build -p mod -dtOa "-std=c++17 -fPIC"
        python3 py.py
