name: macos-latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: "Build/Test"
      run: |
        python3 -V
        curl -Lo mkn https://github.com/mkn/mkn/releases/download/latest/mkn_arm_osx
        chmod +x mkn
        KLOG=3 ./mkn clean build -p test -dtOa "-std=c++17 -fPIC"
        python3 py.py
